name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['2.7', '3.6', '3.7', '3.8', '3.9']
    name: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Prepare buildout egg cache
      run: |
        mkdir ~/.buildout
        echo "[buildout]" >> ~/.buildout/default.cfg
        echo "eggs-directory = ~/eggs" >> ~/.buildout/default.cfg
    - name: Cache eggs
      uses: actions/cache@v3
      with:
        path: ~/eggs
        key: ${{ runner.os }}-eggs-${{ matrix.python-version }}-${{ hashFiles('*cfg') }}
        restore-keys: |
          ${{ runner.os }}-eggs-${{ matrix.python-version }}-
    - name: Test
      run: tox --skip-missing-interpreters=false
