name: CI
on:
  push:
    branches:
      - "master"
  pull_request:
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    name: Run tests on all relevant Python versions
    # uses: collective/.github/.github/workflows/tox.yml@main
    # uses: ./.github/workflows/tox.yml
    uses: ./.github/workflows/try.yml
    with:
      # For the strange syntax, see https://github.community/t/reusable-workflow-with-strategy-matrix/205676/8
      # This one fails for me:
      # python-version: >-
      #   ["2.7", "3.6", "3.7", "3.8", "3.9"]
      # python-version: "[\"2.7\", \"3.6\", \"3.7\", \"3.8\", \"3.9\"]"
      # python-version: "[\"2.7\", \"3.6\"]"
      # python-version: '"2.7", "3.6"'
      - py27: true
